### PR TITLE
Use True Black background for Settings again

### PR DESCRIPTION
**Pull request by woshiahmedc**
Use true black for dark mode for Settings. It already committed before as "commit c730588"

### CODE REVIEW

**Comment by thestinger** [comment]
Why? I think we should stick with following Material You.

**Comment by woshiahmedc** [comment]
I thought true black background would be better for battery and eyes in oled screen

**Comment by thestinger** [comment]
Black only makes a tiny difference compared to dark grey for battery life and it doesn't help here since this isn't an app users have open on the screen for hours. Material You is the overall theme for the OS and increasingly for apps, and I don't think it makes much sense to deviate from it when we want to move our own apps towards it and replace legacy AOSP apps partly to provide a consistent Material You theme.

**Comment by woshiahmedc** [comment]
You're right, users don't open it for hours, I thought to apply true black for system-wide, this was a little part of that

**Comment by thestinger** [comment]
We don't choose the theme for apps where users spend most of their time. The websites and apps choose their theme. Ideally, apps would all use Material You for a consistent theme everywhere. Some may decide to use a pure black background but others won't and it really makes very little difference from very dark grey for either battery life or eye strain.

**Comment by woshiahmedc** [comment]
I understand, when I searched about true black mode in GrapheneOS, I saw it approved before while GrapheneOS using default dark theme now and I didn't know the reason, thank you for explanation

**Pull request closed without merging**
